$font = SF Pro Display bold

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/.cache/current_wallpaper
    blur_passes = 3
}

label {
    monitor =
    text = $USER
    font_size = 14
    font_family = $font

    position = 0, 120
    halign = center
    valign = bottom
}

image {
    monitor =
    path = /home/$USER/Pictures/pfp/$USER.jpg
    size = 130
    rounding = 100

    position = 0, 160
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 5%, 3%
    outline_thickness = 2
    inner_color = white

    outer_color = rgba(38, 38, 38, 0.5)
    check_color = rgba(164, 132, 79, 0.5)
    fail_color = rgba(189, 60, 60, 0.5)

    font_color = rgba(38, 38, 38, 1)
    dots_size = 0.2
    fade_on_empty = false
    rounding = 99
    font_family = $font
    placeholder_text = ...
    fail_text = :(
    dots_spacing = 0.3

    position = 0, 70
    halign = center
    valign = bottom
}

# TIME
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M" 
    font_size = 90
    font_family = $font

    position = 0, -70
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 15
    font_family = $font

    position = 0, -230
    halign = center
    valign = top
}