# ──────────────────────────────────────────────────────────────────────────────────── >
#    _   _                  _                 _ 
#   | | | |                | |               | |
#   | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#   |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#   | | | | |_| | |_) | |  | | (_| | | | | (_| |
#   \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#           __/ | |                             
#          |___/|_|       //Autostart
#
# ──────────────────────────────────────────────────────────────────────────────────── >

exec-once = waybar
exec-once = swww-daemon
exec-once = discord &
exec-once = openrgb &
exec-once = wal -R
exec-once = source ~/.cache/wal/colors.sh
