# ──────────────────────────────────────────────────────────────────────────────────── >
#    _   _                  _                 _ 
#   | | | |                | |               | |
#   | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#   |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#   | | | | |_| | |_) | |  | | (_| | | | | (_| |
#   \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#           __/ | |                             
#          |___/|_|       //Autostart
#
# ──────────────────────────────────────────────────────────────────────────────────── >

exec-once = hyprlock
exec-once = waybar
exec-once = swww-daemon
exec-once = sleep 2 && discord &
exec-once = sleep 2 && openrgb &
exec-once = source ~/.cache/wal/colors.sh
exec-once = swaync
exec-once = wl-paste --watch cliphist -db-path /tmp/cliphist-db store
exec-once = hyprsunset