# ──────────────────────────────────────────────────────────────────────────────────── >
#    _   _                  _                 _ 
#   | | | |                | |               | |
#   | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#   |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#   | | | | |_| | |_) | |  | | (_| | | | | (_| |
#   \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#           __/ | |                             
#          |___/|_|       //Monitors
#
# ──────────────────────────────────────────────────────────────────────────────────── >

monitor = HDMI-A-1, 1920x1080@99.65Hz, 0x0, 1