# ──────────────────────────────────────────────────────────────────────────────────── >
#    _   _                  _                 _ 
#   | | | |                | |               | |
#   | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#   |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#   | | | | |_| | |_) | |  | | (_| | | | | (_| |
#   \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#           __/ | |                             
#          |___/|_|       //Rules
#
# ──────────────────────────────────────────────────────────────────────────────────── >

layerrule = animation slide top, blur on, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = animation slide top, blur on, ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = animation slide bottom, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace gtk-layer-shell
windowrule = opacity 1.0 override 0.5 override, match:class firefox
windowrule = opacity 1.0 override 0.5 override, match:class steam_app_[0-9]+

windowrule = no_blur on, match:title Open Files|Open File|Save File|Save As
windowrule = opaque on, match:title Open Files|Open File|Save File|Save As
windowrule = rounding 0, match:title Open Files|Open File|Save File|Save As
windowrule = border_size 0, match:title Open Files|Open File|Save File|Save As
windowrule = no_shadow on, match:title Open Files|Open File|Save File|Save As