# ──────────────────────────────────────────────────────────────────────────────────── >
#    _   _                  _                 _ 
#   | | | |                | |               | |
#   | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
#   |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#   | | | | |_| | |_) | |  | | (_| | | | | (_| |
#   \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#           __/ | |                             
#          |___/|_|       //Rules
#
# ──────────────────────────────────────────────────────────────────────────────────── >

# suppress maximize requests
windowrule = suppressevent maximize, class:.*

# fixed opacity rules
windowrulev2 = opacity 1.0 override 0.8 override, class:^(firefox)$
windowrulev2 = opacity 1.0 override, class:^(steam_app_[0-9]+)$

# fix xwayland drag issue
windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0